# Generated by Django 3.2.4 on 2021-07-18 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReleveCompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('nomDestinataire', models.CharField(max_length=254, null=True)),
                ('montant', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('signataire1', models.CharField(max_length=254, null=True)),
                ('signataire2', models.CharField(max_length=254, null=True)),
                ('signataire3', models.CharField(max_length=254, null=True)),
            ],
        ),
    ]
